version: '3'

volumes:
  {{ cookiecutter.project_slug }}_postgres_data: {}

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - {{ cookiecutter.project_slug }}_postgres_data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_USER={{ cookiecutter.db_user }}
      - POSTGRES_PASSWORD={{ cookiecutter.db_password }}
      - POSTGRES_DB={{ cookiecutter.db_name }}
    ports:
      - "{{ cookiecutter.db_port }}:5432"
    networks:
        - "{{ cookiecutter.project_slug }}_network"

  admin:
    image: {{ cookiecutter.project_slug }}/admin
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        EXTRA_DEP: "admin,dev,testing,local"
    stdin_open: true # For ipdb
    tty: true
    links:
      - postgres:postgres
    working_dir: /app
    volumes:
      - type: bind
        source: ./src
        target: /app
    env_file:
      - ./environments/admin/${ADMIN_ENVIRONMENT}/django.env
      - ./environments/admin/${ADMIN_ENVIRONMENT}/postgres.env
    environment:
      DJANGO_SETTINGS_MODULE: settings.admin.env_local
      DJANGO_PORT: ${ADMIN_DJANGO_PORT}
    ports:
      - "${ADMIN_HOST_PORT}:${ADMIN_DJANGO_PORT}"
    command: /start
    depends_on:
      - postgres
    networks:
      - "{{ cookiecutter.project_slug }}_network"

  api:
    restart: always
    image: {{ cookiecutter.project_slug }}/api
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        EXTRA_DEP: "api,dev,testing,local"
    stdin_open: true # For ipdb
    tty: true
    links:
      - postgres:postgres
    working_dir: /app
    volumes:
      - type: bind
        source: ./src
        target: /app
    env_file:
      - ./environments/api/${API_ENVIRONMENT}/django.env
      - ./environments/api/${API_ENVIRONMENT}/postgres.env
    environment:
      DJANGO_SETTINGS_MODULE: settings.api.env_local
      DJANGO_PORT: ${API_DJANGO_PORT}
    ports:
      - "${API_HOST_PORT}:${API_DJANGO_PORT}"
    command: /start
    networks:
      - "{{ cookiecutter.project_slug }}_network"
    depends_on:
      - postgres
networks:
  {{ cookiecutter.project_slug }}_network:
