#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${DJANGO_POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export DJANGO_POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${DJANGO_POSTGRES_USER}:${DJANGO_POSTGRES_PASSWORD}@${DJANGO_POSTGRES_HOST}:${DJANGO_POSTGRES_PORT}/${DJANGO_POSTGRES_DB}"

python << END
import sys
import time
import psycopg

suggest_unrecoverable_after = 30
start = time.time()
while True:
    try:
        psycopg.connect(
            dbname="${DJANGO_POSTGRES_DB}",
            user="${DJANGO_POSTGRES_USER}",
            password="${DJANGO_POSTGRES_PASSWORD}",
            host="${DJANGO_POSTGRES_HOST}",
            port="${DJANGO_POSTGRES_PORT}",
        )
        break
    except psycopg.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become available...\n")
        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))
    time.sleep(1)
END

>&2 echo 'PostgreSQL is available'

exec "$@"
